# Generated by Django 3.0 on 2020-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20200614_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='per',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
