# Generated by Django 3.0 on 2020-06-16 08:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_auto_20200615_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='plan_img'),
        ),
    ]
