# Generated by Django 3.0 on 2020-06-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_plan_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='benefit1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit10',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit11',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit5',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit6',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit7',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit8',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='plan',
            name='benefit9',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
