# Generated by Django 3.0 on 2020-06-23 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_auto_20200623_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='must be a valid phone number', regex='^[0]\\d{10}$')]),
        ),
    ]
