# Generated by Django 3.0 on 2020-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20200623_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='dateBooked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
