# Generated by Django 3.0 on 2020-06-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_auto_20200623_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
