# Generated by Django 3.0 on 2020-06-23 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_auto_20200623_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
