# Generated by Django 3.0 on 2020-06-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0013_auto_20200623_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
