# Generated by Django 3.0 on 2020-06-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_booking_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
    ]
