# Generated by Django 3.0 on 2020-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0017_auto_20200707_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expiresDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
