# Generated by Django 3.0 on 2020-07-12 17:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0019_auto_20200709_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='plan_img'),
        ),
    ]
