# Generated by Django 3.0 on 2020-06-15 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200614_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
