# Generated by Django 3.0 on 2020-06-14 13:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_event_happyclients'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='about_image')),
                ('description', models.TextField()),
                ('mission', models.TextField()),
                ('visions', models.TextField()),
                ('value1', models.CharField(max_length=150)),
                ('value2', models.CharField(max_length=150)),
                ('value3', models.CharField(blank=True, max_length=150)),
                ('value4', models.CharField(blank=True, max_length=150)),
                ('twitter', models.URLField(blank=True, max_length=250)),
                ('instangram', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('seg_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='seg_image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='happyclients',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.RemoveField(
            model_name='service',
            name='url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='events_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='events_image'),
        ),
        migrations.AddField(
            model_name='happyclients',
            name='client_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='client_image'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='service_image'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='team_image'),
        ),
    ]
