# Generated by Django 3.0 on 2020-06-18 01:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200614_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='mission_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='mission_image'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='value_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='value_image'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='visions_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='visions_image'),
        ),
    ]
