# Generated by Django 3.0 on 2020-07-06 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20200619_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='must be a valid phone number', regex='^[0]\\d{10}$')])),
                ('email', models.EmailField(max_length=200)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
