# Generated by Django 3.0 on 2020-07-12 17:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20200709_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='about_image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='mission_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='mission_image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='value_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='value_image'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='visions_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='vissions_image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='events_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='events_image'),
        ),
        migrations.AlterField(
            model_name='happyclients',
            name='client_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='client_image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='service_image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='team_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='team_image'),
        ),
    ]
